import React, { useState } from "react";
import { Printer, Download, X, Loader2, Edit3 } from "lucide-react";

export default function PdfPreviewModal({
  open,
  onClose,
  tabLabels,
  activeTab,
  officeScope,
  user,
  isExportingPdf,
  onDownloadPDF,
  onPrintPDF,
  filteredVenueBookings,
  filteredEquipmentBorrowings,
  filteredRuleViolations,
  filteredInventoryItems,
  filteredUnits,
  currentVenueNotes,
  currentEquipNotes,
  currentBreachesNotes,
}) {
  const [editableReportTitle, setEditableReportTitle] = useState("Inventory and stock report");
  const [editableVenueNotes, setEditableVenueNotes] = useState(currentVenueNotes || "");
  const [editableEquipNotes, setEditableEquipNotes] = useState(currentEquipNotes || "");
  const [editableBreachesNotes, setEditableBreachesNotes] = useState(currentBreachesNotes || "");

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-[2000] bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 animate-in fade-in duration-200">
      <div className="bg-white rounded-3xl border border-slate-200 shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden">
        {/* Modal Header */}
        <div className="flex items-center justify-between p-4 sm:p-5 border-b border-slate-100 shrink-0 bg-slate-50/90">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-blue-50 text-blue-600">
              <Printer size={18} />
            </div>
            <div>
              <p className="text-xs font-bold text-slate-800">
                Inventory and stock report
              </p>
              <div className="flex items-center gap-1.5 text-[10px] text-blue-600 font-semibold mt-0.5">
                <Edit3 size={11} />
                <span>Editable Preview — Click any text below to customize before export</span>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              disabled={isExportingPdf}
              onClick={onDownloadPDF}
              className="flex items-center gap-1.5 px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-extrabold shadow-xs cursor-pointer transition-all disabled:opacity-50"
              title="Download and save as PDF file to device"
            >
              {isExportingPdf ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}
              <span>{isExportingPdf ? "Saving PDF..." : "Download PDF File"}</span>
            </button>
            <button
              type="button"
              onClick={onPrintPDF}
              className="flex items-center gap-1.5 px-3.5 py-2 bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 rounded-xl text-xs font-extrabold shadow-xs cursor-pointer transition-all"
              title="Print paper copy"
            >
              <Printer size={14} />
              <span>Print</span>
            </button>
            <button
              type="button"
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-slate-600 rounded-lg cursor-pointer"
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Printable Report Document Body */}
        <div id="printable-report-area" className="p-8 overflow-y-auto space-y-6 text-xs print:p-0 font-sans">
          {/* Official Document Letterhead */}
          <div className="text-center border-b-2 border-slate-900 pb-4 space-y-1">
            <p className="text-[11px] font-bold text-slate-500 uppercase tracking-wider">
              Father Saturnino Urios University
            </p>
            <h2 className="text-base font-black text-slate-900 tracking-tight uppercase">
              Audio-Visual Resource Center (AVRC)
            </h2>
            <h3
              contentEditable
              suppressContentEditableWarning
              onBlur={(e) => setEditableReportTitle(e.currentTarget.textContent || "Inventory and stock report")}
              className="text-sm font-extrabold text-blue-900 hover:bg-blue-50/50 p-1 rounded transition-colors focus:outline-none focus:ring-1 focus:ring-blue-400"
              title="Click to edit report title"
            >
              {editableReportTitle}
            </h3>
            <div className="flex items-center justify-center gap-3 text-[10.5px] font-semibold text-slate-500 pt-1">
              <span>Date Generated: <strong>{new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</strong></span>
              <span>•</span>
              <span>Generated By: <strong>{user?.name || "System Admin"}</strong></span>
            </div>
          </div>

          {/* Tab Data Table for PDF */}
          {activeTab === "booking_borrowing" && (
            <div className="space-y-6">
              {/* 1. Venue Bookings Table */}
              <div className="space-y-2">
                <h4 className="font-extrabold text-xs text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-1">
                  Venue Reservation Records ({filteredVenueBookings.length} total)
                </h4>
                <table className="w-full text-[11px] border border-slate-300">
                  <thead className="bg-slate-100">
                    <tr>
                      {["#", "Track No.", "Requestor", "Venue", "Schedule", "Department", "Purpose", "Status"].map(h => (
                        <th key={h} className="border border-slate-300 p-2 text-left font-bold">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {filteredVenueBookings.length === 0 ? (
                      <tr>
                        <td colSpan={8} className="border border-slate-300 p-3 text-center text-slate-400">
                          No venue booking records found.
                        </td>
                      </tr>
                    ) : (
                      filteredVenueBookings.map((b, i) => (
                        <tr key={i} className="border-b border-slate-200">
                          <td className="border border-slate-300 p-2 text-center text-slate-500 font-bold">{i + 1}</td>
                          <td className="border border-slate-300 p-2 font-mono font-bold text-blue-700">{b.trackingNumber?.reference_code || b.reference_code || `TRK-AVR${b.id}`}</td>
                          <td className="border border-slate-300 p-2 font-bold text-slate-900">{b.filer_name || b.requestor_name || "—"}</td>
                          <td className="border border-slate-300 p-2 font-semibold text-slate-800">{b.venue?.name || "AVR Main Hall"}</td>
                          <td className="border border-slate-300 p-2 font-mono text-[10px]">{b.start_datetime ? new Date(b.start_datetime).toLocaleDateString() : "—"}</td>
                          <td className="border border-slate-300 p-2 text-slate-700">{b.department || b.department_name || "—"}</td>
                          <td className="border border-slate-300 p-2 text-slate-700 max-w-[150px] truncate">{b.purpose || b.activity_name || "—"}</td>
                          <td className="border border-slate-300 p-2 font-bold uppercase text-[10px]">{b.status || b.trackingNumber?.status || "PENDING"}</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>

                {/* Venue Report Remarks */}
                <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-xl space-y-1 mt-2">
                  <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-500 block">
                    Remarks:
                  </span>
                  <div
                    contentEditable
                    suppressContentEditableWarning
                    onBlur={(e) => setEditableVenueNotes(e.currentTarget.textContent || "")}
                    className="text-[11px] text-slate-800 leading-relaxed font-medium whitespace-pre-wrap hover:bg-white p-1 rounded transition-colors focus:outline-none focus:ring-1 focus:ring-blue-400"
                    title="Click to edit remarks"
                  >
                    {editableVenueNotes || "No specific observations or executive remarks recorded for venue reservations."}
                  </div>
                </div>
              </div>

              {/* 2. Equipment Borrowing Table */}
              <div className="space-y-2 pt-2 border-t border-slate-200">
                <h4 className="font-extrabold text-xs text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-1">
                  Equipment Borrowing Records ({filteredEquipmentBorrowings.length} total)
                </h4>
                <table className="w-full text-[11px] border border-slate-300">
                  <thead className="bg-slate-100">
                    <tr>
                      {["#", "Track No.", "Requestor", "Department", "Equipment Units", "Schedule", "Status"].map(h => (
                        <th key={h} className="border border-slate-300 p-2 text-left font-bold">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {filteredEquipmentBorrowings.length === 0 ? (
                      <tr>
                        <td colSpan={7} className="border border-slate-300 p-3 text-center text-slate-400">
                          No equipment borrowing records found.
                        </td>
                      </tr>
                    ) : (
                      filteredEquipmentBorrowings.map((b, i) => (
                        <tr key={i} className="border-b border-slate-200">
                          <td className="border border-slate-300 p-2 text-center text-slate-500 font-bold">{i + 1}</td>
                          <td className="border border-slate-300 p-2 font-mono font-bold text-blue-700">{b.trackingNumber?.reference_code || b.reference_code || `TRK-EQP${b.id}`}</td>
                          <td className="border border-slate-300 p-2 font-bold text-slate-900">{b.filer_name || b.requestor_name || "—"}</td>
                          <td className="border border-slate-300 p-2 text-slate-700">{b.department || b.department_name || "—"}</td>
                          <td className="border border-slate-300 p-2 font-semibold text-slate-800">
                            {b.items && b.items.length > 0
                              ? b.items.map(it => `${it.quantity_requested || 1}x ${it.equipmentType?.name || it.equipment_type?.name || 'Item'}`).join(', ')
                              : (b.equipment_name || "AV Equipment")}
                          </td>
                          <td className="border border-slate-300 p-2 font-mono text-[10px]">
                            {b.start_datetime ? `${new Date(b.start_datetime).toLocaleDateString()}` : "—"}
                          </td>
                          <td className="border border-slate-300 p-2 font-bold uppercase text-[10px]">{b.status || b.trackingNumber?.status || "PENDING"}</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>

                {/* Equipment Report Remarks */}
                <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-xl space-y-1 mt-2">
                  <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-500 block">
                    Remarks:
                  </span>
                  <div
                    contentEditable
                    suppressContentEditableWarning
                    onBlur={(e) => setEditableEquipNotes(e.currentTarget.textContent || "")}
                    className="text-[11px] text-slate-800 leading-relaxed font-medium whitespace-pre-wrap hover:bg-white p-1 rounded transition-colors focus:outline-none focus:ring-1 focus:ring-blue-400"
                    title="Click to edit remarks"
                  >
                    {editableEquipNotes || "No specific observations or executive remarks recorded for equipment borrowings."}
                  </div>
                </div>
              </div>
            </div>
          )}

          {activeTab === "breaches" && (
            <div className="space-y-4">
              <h4 className="font-extrabold text-xs text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-1">
                Department Breach &amp; Late Return Summary
              </h4>
              <table className="w-full text-[11px] border border-slate-300">
                <thead className="bg-slate-100">
                  <tr>
                    {["#", "Department / Program", "Venue Breaches", "Equipment Violations Summary"].map(h => (
                      <th key={h} className="border border-slate-300 p-2 text-left font-bold">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {filteredRuleViolations.length > 0 ? (
                    filteredRuleViolations.map((v, i) => (
                      <tr key={i}>
                        <td className="border border-slate-300 p-2 font-bold">{i + 1}</td>
                        <td className="border border-slate-300 p-2 font-bold">{v.department || v.program || "Academic Dept"}</td>
                        <td className="border border-slate-300 p-2 text-rose-600 font-bold">{v.venue_violations ?? 0} Breaches</td>
                        <td className="border border-slate-300 p-2 font-bold text-slate-800">
                          {`${v.late_returns || 0} Late Return / ${v.equipment_damages || 0} Damaged / ${v.equipment_lost || 0} Lost`}
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan={4} className="border border-slate-300 p-4 text-center text-slate-400">No department breaches recorded in this audit cycle.</td>
                    </tr>
                  )}
                </tbody>
              </table>

              {/* Violations Report Remarks */}
              <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-xl space-y-1">
                <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-500 block">
                  Remarks:
                </span>
                <div
                  contentEditable
                  suppressContentEditableWarning
                  onBlur={(e) => setEditableBreachesNotes(e.currentTarget.textContent || "")}
                  className="text-[11px] text-slate-800 leading-relaxed font-medium whitespace-pre-wrap hover:bg-white p-1 rounded transition-colors focus:outline-none focus:ring-1 focus:ring-blue-400"
                  title="Click to edit remarks"
                >
                  {editableBreachesNotes || "No specific disciplinary remarks or compliance recommendations recorded."}
                </div>
              </div>
            </div>
          )}

          {activeTab === "inventory" && (
            <div className="space-y-6">
              {/* 1. Inventory and Stock Summary Table */}
              <div className="space-y-2">
                <h4 className="font-extrabold text-xs text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-1">
                  Inventory and Stock Summary ({filteredInventoryItems.length} Categories)
                </h4>
                <table className="w-full text-[11px] border border-slate-300">
                  <thead className="bg-slate-100">
                    <tr>
                      {["Item Code", "Category / Equipment Name", "Expected Total", "Present Available", "Reserved", "Released", "Damaged", "Lost", "Remarks"].map(h => (
                        <th key={h} className="border border-slate-300 p-2 text-left font-bold">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {filteredInventoryItems.length === 0 ? (
                      <tr>
                        <td colSpan={9} className="border border-slate-300 p-3 text-center text-slate-400">
                          No equipment stock inventory records found.
                        </td>
                      </tr>
                    ) : (
                      filteredInventoryItems.map((item, idx) => (
                        <tr key={idx} className="border-b border-slate-200">
                          <td className="border border-slate-300 p-2 font-mono font-bold text-slate-700">EQ-00{idx + 1}</td>
                          <td className="border border-slate-300 p-2 font-bold text-slate-900">{item.eq_type || item.eq_name || item.name || "Equipment"}</td>
                          <td className="border border-slate-300 p-2 text-center font-bold">{item.calculated_total ?? item.total_quantity ?? 0}</td>
                          <td className="border border-slate-300 p-2 text-center font-bold text-emerald-600">{item.calculated_available ?? item.available_count ?? 0}</td>
                          <td className="border border-slate-300 p-2 text-center font-bold text-indigo-600">{item.reserved_count ?? item.reserved ?? 0}</td>
                          <td className="border border-slate-300 p-2 text-center font-bold text-blue-600">{item.released_count ?? 0}</td>
                          <td className="border border-slate-300 p-2 text-center font-bold text-rose-600">{item.damaged_count ?? 0}</td>
                          <td className="border border-slate-300 p-2 text-center font-bold text-amber-600">{item.lost_count ?? 0}</td>
                          <td className="border border-slate-300 p-2 text-slate-600">{item.description || "—"}</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>

              {/* 2. Equipment Units Table */}
              <div className="space-y-2 pt-2 border-t border-slate-200">
                <h4 className="font-extrabold text-xs text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-1">
                  equipment units ({filteredUnits.length} Units Registered)
                </h4>
                <table className="w-full text-[11px] border border-slate-300">
                  <thead className="bg-slate-100">
                    <tr>
                      {["#", "Unit Barcode", "Equipment Unit Name", "Assigned Category", "Status", "Condition", "Date Purchased", "Lifespan"].map(h => (
                        <th key={h} className="border border-slate-300 p-2 text-left font-bold">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {filteredUnits.length === 0 ? (
                      <tr>
                        <td colSpan={8} className="border border-slate-300 p-3 text-center text-slate-400">
                          No physical equipment units found.
                        </td>
                      </tr>
                    ) : (
                      filteredUnits.map((u, i) => (
                        <tr key={i} className="border-b border-slate-200">
                          <td className="border border-slate-300 p-2 text-center text-slate-500 font-bold">{i + 1}</td>
                          <td className="border border-slate-300 p-2 font-mono font-bold text-blue-700">{u.barcode || u.unit_code || `UNIT-${u.id}`}</td>
                          <td className="border border-slate-300 p-2 font-semibold text-slate-900">{u.name || "Equipment Unit"}</td>
                          <td className="border border-slate-300 p-2">{u.category || "AV Equipment"}</td>
                          <td className="border border-slate-300 p-2 font-bold uppercase text-[10px]">{u.status || "AVAILABLE"}</td>
                          <td className="border border-slate-300 p-2 font-bold">
                            <span className={u.condition === "Damaged" ? "text-rose-600" : (u.condition === "Lost" ? "text-amber-600" : "text-emerald-600")}>
                              {u.condition || "Good"}
                            </span>
                          </td>
                          <td className="border border-slate-300 p-2 text-slate-600">{u.date_purchased || "—"}</td>
                          <td className="border border-slate-300 p-2 text-slate-600">{u.lifespan_years || 5} yrs</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Sign-off footer */}
          <div className="pt-8 flex justify-between items-end border-t border-slate-200 text-[11px]">
            <div>
              <p className="text-slate-400 font-medium">Certified Official Audit Copy</p>
              <p className="font-extrabold text-slate-800">Father Saturnino Urios University</p>
            </div>
            <div className="text-right space-y-8">
              <p className="font-medium text-slate-500">Prepared &amp; Verified By:</p>
              <div className="border-t border-slate-900 pt-1 font-bold text-slate-900">
                {user?.name || "AVR Administrator"}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
